before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
checksum:
  name_template: "checksums.txt"
brews:
  - name: git-semver
    description: Automatically derive semantic versions from Git tags.
    homepage: https://github.com/mdomke/git-semver
    repository:
      owner: mdomke
      name: homebrew-git-semver
    skip_upload: auto
