before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
brews:
  - name: git-semver
    description: Automatically derive semantic versions from Git tags.
    homepage: https://github.com/mdomke/git-semver
    tap:
      owner: mdomke
      name: homebrew-git-semver
    skip_upload: auto
